{{ if eq .Params.ENABLE_CRUISE_CONTROL "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}-cruise-control
  namespace: {{ .Namespace }}
spec:
  selector:
    matchLabels:
      app: cruise-control
  replicas: 1
  template:
    metadata:
      labels:
        app: cruise-control
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: cruise-control
        image: zmalikshxil/cruise-control:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9090
        command:
          - bash
          - -c
        args:
          - /opt/cruise-control/start.sh
        env:
          - name: CRUISE_CONTROL_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CRUISE_CONTROL_INSTANCE_NAME
            value: "{{ .Name }}"
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        readinessProbe:
          tcpSocket:
            port: 9090
          timeoutSeconds: 1
        volumeMounts:
        - name: cc-props
          mountPath: /etc/cruise-control/config
      volumes:
      - name: cc-props
        configMap:
          name: {{ .Name }}-cruisecontrol-props
{{ end }}